name: sleep
description: Great collection of high-definition sounds that can be mixed into relaxing ambiances

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  audio_video_progress_bar: ^0.10.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  just_audio: ^0.9.24
  just_audio_web: ^0.4.7
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  flutter_svg: ^1.0.0
  flutter_blue_plus: ^1.4.0
  flutter_bluetooth_serial: ^0.3.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2
  scoped_model: ^2.0.0-nullsafety.0
  flutter_speech: ^2.0.0
  provider: ^6.0.1
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Light.ttf
          weight: 300
        - asset: assets/Roboto-Regular.ttf
          weight: 400
        - asset: assets/Roboto-Medium.ttf
          weight: 500
        - asset: assets/Roboto-Bold.ttf
          weight: 700
